# Generated by Django 4.1 on 2022-09-20 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
