# Generated by Django 4.1 on 2022-09-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
